# basic checks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-symlinks
  - id: no-commit-to-branch
  - id: end-of-file-fixer
    exclude: ^tests/batch/_gbasf2_project_download_stdouts/
  - id: fix-byte-order-marker

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
