[build-system]
requires = ["uv_build>=0.12.18,<0.13"]
build-backend = "uv_build"

[project]
name = "b2luigi"
version = "1.2.9"
description = "b2luigi - bringing batch 2 luigi"
readme = "README.rst"
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name = "Nils Braun, Michael Eliachevitch, The Belle II Collaboration", email = "software-b2luigi@belle2.org"},
]
keywords = ["luigi", "workflow management", "belle2"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
dependencies = [
    "luigi>=3.0.2",
    "parse>=1.8.4",
    "GitPython>=2.1.11",
    "colorama>=0.3.9",
    "cachetools>=2.1.0",
    "jinja2",
    "tenacity>=8,<9",
    "webdavclient3>=3.14.7",
    "xrootd>=5.7.0",
    "typer>=0.12.0",
    "shellingham>=1.5",
    "click>=8.0.0"
]

[project.scripts]
b2luigi = "b2luigi.cli:main"

[project.optional-dependencies]
tui = [
    "textual>=8.0.0",
]

[project.urls]
Homepage = "https://github.com/belle2/b2luigi"
Documentation = "https://b2luigi.belle2.org/"
"Bug Tracker" = "https://gitlab.desy.de/belle2/software/b2luigi/-/issues"
Changelog = "https://gitlab.desy.de/belle2/software/b2luigi/-/releases"

[dependency-groups]
test = [
    "pytest",
    "pytest-cov",
    "python-coveralls",
]
# Use the same versions of sphinx and sphinx-book-theme
# as in the latest version of the basf2 externals
# (see https://github.com/belle2/externals)
docs = [
    "sphinx",
    "sphinx-book-theme",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-devhelp",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-qthelp",
    "sphinxcontrib-serializinghtml",
    "sphinxcontrib-typer",
    "sphinx-gallery",
    "sphinx-autobuild",
    "sphinx-sitemap",
    "sphinx-notfound-page",
]
dev = [
    "pre_commit",
    {include-group = "test"},
    {include-group = "docs"},
]

[tool.uv.build-backend]
module-root = "."

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.ruff]
line-length = 120

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401", "F403", "E402"]
"examples/gbasf2/example_mdst_analysis.py" = ["E501"]
"examples/tutorial/Ex13_plot_invariant_mass.py" = ["E402"]

[tool.pytest.ini_options]
addopts = "-p no:pylama"
