[build-system]
requires = ["flit_core>=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "b2luigi"
dynamic = ["version", "description"]
authors = [
    {name = "Nils Braun, Michael Eliachevitch, The Belle II Collaboration", email = "software-b2luigi@belle2.org"},
]
license = "GPL-3.0-or-later"
keywords = ["luigi", "workflow management", "belle2"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
dependencies = [
	 "luigi>=3.0.2",
	 "parse>=1.8.4",
	 "GitPython>=2.1.11",
	 "colorama>=0.3.9",
	 "cachetools>=2.1.0",
	 "jinja2",
     "setuptools",
	 "tenacity>=8,<9",
     "webdavclient3>=3.14.7",
     "typer>=0.12.0",
     "shellingham>=1.5",
     "click>=8.0.0"
]
requires-python = ">=3.11"
readme = "README.rst"

[project.scripts]
b2luigi = "b2luigi.cli:main"

[project.optional-dependencies]
tui = [
    "textual>=8.0.0",
]
# Use the same versions of sphinx and sphinx-book-theme
# as in the latest version of the basf2 externals
# (see https://github.com/belle2/externals)
doc = [
    "sphinx",
    "sphinx-book-theme",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-devhelp",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-qthelp",
    "sphinxcontrib-serializinghtml",
    "sphinxcontrib-typer",
    "sphinx-gallery",
    "sphinx-autobuild",
    "sphinx-sitemap",
    "sphinx-notfound-page",
]
dev = [
    "pre_commit",
    "pytest",
    "pytest-cov",
    "python-coveralls",
    "bump-my-version"
]

[project.urls]
Homepage = "https://github.com/belle2/b2luigi"
Documentation = "https://b2luigi.belle2.org/"

[tool.ruff]
line-length = 120

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401", "F403", "E402"]
"examples/gbasf2/example_mdst_analysis.py" = ["E501"]
"examples/tutorial/Ex13_plot_invariant_mass.py" = ["E402"]

[tool.pytest.ini_options]
addopts = "-p no:pylama"
